### ISSUE TITLE
Fuzzywuzzy 4x slower *with* python-Levenshtein installed

### ISSUE THREAD

**Issue by Hooloovoo** [seatgeek/fuzzywuzzy#91] opened 2015-08-26 10:43 UTC
According to the intro page:
"python-Levenshtein (optional, provides a 4-10x speedup in String Matching)"

I am fuzzy matching paragraphs with their best match from a significant list of paragraphs. When I use fuzzywuzzy without python-Levenshtein on Ubuntu, I receive the error that I should install it for a speed-up, and it took about 45 mins on a test set of paragraphs:

real	46m56.813s
user	125m45.952s
sys	0m0.432s

When I then installed python-Levenshtein, the error went away as expected, but running the same example set of paragraphs took over 200 minutes:

real	204m51.384s
user	522m49.436s
sys	0m21.376s

The results are identical except for one paragraph, which does match better with the slower, python-Levenshtein version. While I haven't timed an example, doing the same on the mac also seems significantly slower with python-Levenshtein installed.

The error message when python-Levenshtein is not installed says that the reason to install the package is for speed, so to me something isn't right: either it shouldn't be slower, or the error message should change to say that it should be installed for increased accuracy (if that is the case).

**Comment by josegonzalez** [comment] 2015-08-26 14:05
How did you install python-Levenshtein? Seems like it should be faster, as its compiled code and not pure python.

**Comment by acslater00** [comment] 2015-08-26 14:07
Would you mind posting a gist containing a reproduction?

**Comment by Hooloovoo** [comment] 2015-08-26 18:02
Thank you for your quick replies.
I'm installing it with pip.
I've tried to create a simple test case with non-private data and it is acting as you would expect (with Levenshtein significantly faster). I'll therefore need to work from my real code and strip it back until it's as simple as possible while still exhibiting the same behaviour. It may take me a little bit, though.

**Comment by josegonzalez** [comment] 2015-11-16 07:00
@Hooloovoo friendly *bump* :)

**Comment by josegonzalez** [comment] 2016-07-22 20:49
Closing as there hasn't been an update in a while.

**Closed by josegonzalez** 2016-07-22 20:49 UTC
Labels: needs more info

**Comment by markdall** [comment] 2019-02-22 20:46
I've never NOT been able to reproduce this. I can give you files if you really need them to reproduce this with, maybe it will turn out I'm using partial_ratio in ways it's not meant to be used.

**Comment by josegonzalez** [comment] 2019-02-22 22:02
A pull request with tests attached would be great, so we can verify your issue across all supported python versions :)

**Comment by markdall** [comment] 2019-02-23 00:43
Ok, but first here's your opportunity to say I'm just using it in an unintended way

benchmarks.py without python-Levenshtein: Total time: 24.497282s. Average run: 244.973ms.
benchmarks.py with python-Levenshtein installed: Total time: 1.687531s. Average run: 16.875ms.

So far so good right? It's much faster. But that's not how I'm using it. 

I'm using it with a 130k (for example, sometimes larger) file and comparing it to a series of files that are 3-8k in size. Basically I'm comparing build logs to snippets of other logs I've saved and identified as bugs, the idea being to automate identifying other bugs. 

Still interested?

**Comment by josegonzalez** [comment] 2019-02-23 15:24
Yep, but again, we'll need these as test cases in a PR.

**Comment by ercas** [comment] 2021-01-04 19:35
@josegonzalez hi, i'm also able to reproduce this consistently by comparing AcoustID fingerprint vectors... is there an example of what the PR should look like?

**Comment by josegonzalez** [comment] 2021-01-20 01:07
We have a benchmark script here: https://github.com/seatgeek/fuzzywuzzy/blob/master/benchmarks.py

I assume there is _some_ way to have these get reported back somewhere, so would be good to get them to run in CI and see if the benchmarks still hold true. Its possible that using python-levenshtein is slower for some class of strings and not others.
