### ISSUE TITLE
Find term position

### ISSUE THREAD

**Issue by MahmoudAliEng** [seatgeek/fuzzywuzzy#294] opened 2020-12-13 15:07 UTC
I'm using `fuzz.token_set_ratio(str1, str2)` to find str1 in str2 (str1 may not be in the same format as it appears in str2 : up/low case, space between letters, punctuation ...) and it's doing just a great job.

What I need is to find the term position if it exists in the second string. Is that possible with fuzzywuzzy ? Or is there any method to achieve that ?

Thank you for your help.

**Comment by s-c-p** [comment] 2020-12-13 15:33
Duplicate of #293

Suggest merge/close with prior https://github.com/seatgeek/fuzzywuzzy/issues/293

**Closed** 2020-12-22 06:53 UTC
